name: template
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  shqs_util:
    path: packages/shqs_util
  string_validator: ^0.3.0

  #State Management, Route Management & Dependency Injection
  get: ^4.3.8

  #Animation
  lottie: ^1.1.0

  #Reactive Dart Libraries
  dart_date: ^1.1.1
  dartz: ^0.10.1

  #Networking
  dio: ^4.0.6
  retrofit: ^3.3.1

  #Image Processing
  #cached_network_image:

  #Local Storage
  #shared_preferences: ^2.0.13
  sqflite: ^2.1.0+1
  floor: ^1.3.0
  floor_annotation: ^1.3.0

  #State Management
  provider: ^6.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3

  #Code Analysis
  lint: ^1.6.0

  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: any
  freezed_annotation: any
  floor_generator: any
  json_serializable:
  analyzer: any
  retrofit_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  generate: true