name: template
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #Util libraries
  shqs_util:
    path: packages/shqs_util
  string_validator: ^0.3.0

  #State Management, Route Management & Dependency Injection
  get: ^4.3.8

  #Animation
  lottie: ^1.1.0

  #Reactive Dart Libraries
  dart_date: ^1.1.0
  dartz: ^0.10.0

  #Networking
  dio: ^4.0.0
  retrofit: ^2.0.1

  #Image Processing
  cached_network_image:

  #Local Storage
  shared_preferences: ^2.0.12
  sqflite: ^2.0.0+3
  floor: ^1.1.0
  floor_annotation: ^1.0.0

  #State Management
  provider: ^6.0.2
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3

  #Code Analysys
  lint: ^1.6.0

  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  floor_generator: ^1.1.0
  json_serializable:
  analyzer: ^1.1.0
  retrofit_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  generate: true